# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = "blowfish"
baseURL = "https://dscmec-blogs.netlify.app/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 20
summaryLength = 20

buildDrafts = false
buildFuture = false

googleAnalytics = "G-07RYNVBGK6"

[taxonomies]
  tag = "tags"
  # category = "categories"
  author = "authors"
  # series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
