version: "3"
services:
  dsmec-blogs:
    container_name: dsmec-blogs
    build:
      context: .
    # environment:
    #   - VIRTUAL_HOST=dscblogs.mec.ac.in
    # restart: "always"

# networks:
#   default:
#     external:
#       name: mec
