name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Hugo
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v0.76.5/hugo_0.105.0_Linux-64bit.deb
        sudo dpkg -i hugo_0.105.0_Linux-64bit.deb
    - name: Build site
      run: hugo
    - name: Deploy to production
      run: |
        git config --global user.email "jaisondennis080@gmail.com"
        git config --global user.name "jaison080"
        git add .
        git commit -m "Automated deployment to production"
        git push origin master:production