name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Merge master -> production
      uses: devmasx/merge-branch@master
      with:
          type: now
          from_branch: master
          target_branch: production

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Hugo
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v0.105.0/hugo_0.105.0_linux-amd64.deb
        sudo dpkg -i hugo_0.105.0_linux-amd64.deb
    - name: Checkout Submodule
      run: git submodule update --init --recursive
    - name: Build website
      run: hugo --minify
    - name: Deploy to production
      run: |
        git config --global user.email "jaisondennis080@gmail.com"
        git config --global user.name "jaison080"
        git add .
        git commit -m "Deploy to production"
        git push origin master:production -f
